### ISSUE TITLE
关于api请求链接的问题

### ISSUE THREAD

**Issue by sherlR** [caolvchong-top/twitter_download#11]
![image](https://github.com/caolvchong-top/twitter_download/assets/38378471/5ec69655-a272-4e4d-823f-cbe5fc211648)
那个variables后面就是一连串的字典吗？打印出URL来看着怪怪的
因为我这样请求提示“获取信息失败”，response打印出来是空的，cookie也设置的正确的，所以在想是不是URL格式不对？
希望可以得到解答~

**Comment by caolvchong-top** [comment]
异步部分的代码貌似有点问题

**Comment by caolvchong-top** [comment]
![image](https://github.com/caolvchong-top/twitter_download/assets/57820488/9c866bf2-acfe-4a56-9743-555ccbcd9dee)
首先需确认程序运行时是否出现如图信息，出现则运行正常 

其次是他的图片有的很大，容易超时，可以修改代码第222行的超时时间 (我测试时调成了 **(20,40)** ，具体视个人网络情况而定) 

还有一种方案是删去第222行中的**await**，不使用异步，超时时间无需修改 

//这大概是我代码问题，但我暂未找出原因以及改进方法

另外关于请求链接，url应该没错，但它的headers中需要 **[ user-agent, authorization, cookie, x-csrf-token, referer ]** 这几个参数，可以检查一下是否配齐

**Comment by sherlR** [comment]
嗯...是运行失败的
![1697017537755](https://github.com/caolvchong-top/twitter_download/assets/38378471/d8f97a46-39c0-4e99-a1ee-329fd8745d0c)
![1697018062718](https://github.com/caolvchong-top/twitter_download/assets/38378471/c08fbd9b-bc6d-401e-811d-cd1bdb920a75)
![1697017611644](https://github.com/caolvchong-top/twitter_download/assets/38378471/b8adedce-6b3d-4c6b-94ed-069a970d9641)
这是我的运行截图 改成（20,40）也是无法获取信息，我打印出来 headers里是有那五个参数的，请问是我的cookie设置错误了吗 看上去也是该有引号的地方是有的，而且cookie里“auth_token，ct0”这些也是有的
可以问一下您的Python版本吗

**Comment by caolvchong-top** [comment]
我是 Python 3.11 的环境 

获取信息失败大概率是cookie错误，如图：
![image](https://github.com/caolvchong-top/twitter_download/assets/57820488/9102da7e-2b05-4434-8ff9-6e11b9abb832)

可以直接复制完整cookie填入settings(引号前加反斜杠)，或是如 #10 中提到的，仅填写auth_token与ct0

**Comment by caolvchong-top** [comment]
global 的 response 去掉 

在75行后插一句``print(response)`` 

看看输出

**Comment by sherlR** [comment]
![image](https://github.com/caolvchong-top/twitter_download/assets/38378471/4d9eece0-96fb-47ae-821d-f8f61a35718e)
![image](https://github.com/caolvchong-top/twitter_download/assets/38378471/0fbb1dfd-2d43-4ca1-9cf2-c98a518a1ef6)
![image](https://github.com/caolvchong-top/twitter_download/assets/38378471/7bf09125-9b81-4d64-bb68-44a00b925379)
没走到呢就报错了 啊？我才发现
获取信息失败
Traceback (most recent call last):
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_backends\sync.py", line 212, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 850, in create_connection
    raise exceptions[0]
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 835, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 262, in handle_request
    raise exc
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_backends\sync.py", line 211, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\soft\twitter_download-main\main.py", line 75, in get_other_info
    response = httpx.get(url, headers=_headers).text
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_api.py", line 189, in get
    return request(
           ^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\90346\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\soft\twitter_download-main\main.py", line 266, in <module>
    main(User_info(i))
  File "D:\soft\twitter_download-main\main.py", line 251, in main
    if not get_other_info(_user_info):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\soft\twitter_download-main\main.py", line 85, in get_other_info
    print(response)
          ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
这是整个报错信息

**Comment by sherlR** [comment]
![1697029826514](https://github.com/caolvchong-top/twitter_download/assets/38378471/d226a812-2631-4872-9572-2571a1d7f9
![1697029829628](https://github.com/caolvchong-top/twitter_download/assets/38378471/3b4f3a56-c4f6-4d7f-b78e-ba713bb7954c)
e2)
![1697029842710](https://github.com/caolvchong-top/twitter_download/assets/38378471/77ecba44-9725-4447-8051-6179509d2454)
没有走到那个地方呢就报错，get请求就直接报错了？wow，才发现

**Comment by caolvchong-top** [comment]
像是代理问题，开个新文件，试试下面这段代码： 
```
import httpx

url = 'https://www.youtube.com/'

headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
    'referer': 'https://www.youtube.com/'
}

response = httpx.get(url)

print(response.text)
print(f'status_code : {response.status_code}')
```
看看 status_code 是不是200

**Comment by sherlR** [comment]
应该是代理的问题....一样的报错 我第一次遇到这种问题，请问怎么设置呢 麻烦了

**Comment by caolvchong-top** [comment]
这个主要看你用的vpn客户端，看看有没有全局代理选项 

或者 vscode 左下角设置 --> 搜索 **proxy** --> 在代理设置里配置代理服务器 
像这种格式的：
```
http://127.0.0.1:port
```
具体要看你的vpn代理在哪个端口

**Comment by sherlR** [comment]
嗯？我开了全局代理也不行啊，YouTube这些都可以在浏览器打开，但是代码里就这里直接报错
![image](https://github.com/caolvchong-top/twitter_download/assets/38378471/52246d5e-a2f5-46d5-9a64-9d04c68f176c)
那不是代码的问题 应该是我电脑的问题了，我用国内的网站的statecode是 200，也不知道什么原理了。

**Comment by niuyuxuan** [comment]
请问解决了吗？我也遇到这个问题了

**Comment by caolvchong-top** [comment]
> 请问解决了吗？我也遇到这个问题了

代理问题吗？ 

代理问题的话我这边实在没有办法

**Comment by niuyuxuan** [comment]
> > 请问解决了吗？我也遇到这个问题了
> 
> 代理问题吗？
> 
> 代理问题的话我这边实在没有办法
谢谢了，想问一下，这几个url变量需要更换么？然后关于cookie，是用
![test](https://github.com/caolvchong-top/twitter_download/assets/40338208/13285b12-0632-499e-82b9-d8efe2a8565e)
那个文件的呢？

**Comment by caolvchong-top** [comment]
> > 谢谢了，想问一下，这几个url变量需要更换么？然后关于cookie，是用
> > 那个文件的呢？

默认的url不用改，理论可用 
cookie中只要含有 **authtoken** 和 **ct0** 字段即可 #10

**Comment by niuyuxuan** [comment]
> > > 谢谢了，想问一下，这几个url变量需要更换么？然后关于cookie，是用
> > > 那个文件的呢？
> 
> 代码里的url一般不用改，理论可用 cookie中只要含有 **authtoken** 和 **ct0** 字段即可 #10
谢谢了，想问一下你的代理是怎么设置的，是用的代理软件吗？我这边换了两个环境也不成功

**Comment by caolvchong-top** [comment]
我是V2rayNg客户端，默认全局代理，vscode运行程序

**Comment by caolvchong-top** [comment]
> 谢谢了，想问一下你的代理是怎么设置的，是用的代理软件吗？我这边换了两个环境也不成功

我是V2rayNg客户端，默认全局代理，vscode默认配置运行程序

**Comment by niuyuxuan** [comment]
> 像是代理问题，开个新文件，试试下面这段代码：
> 
> ```
> import httpx
> 
> url = 'https://www.youtube.com/'
> 
> headers = {
>     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
>     'referer': 'https://www.youtube.com/'
> }
> 
> response = httpx.get(url, headers=headers)
> 
> print(response.text)
> print(f'status_code : {response.status_code}')
> ```
> 
> 看看 status_code 是不是200

import httpx

url = 'https://www.youtube.com/'

headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
    'referer': 'https://www.youtube.com/'
}

proxies = {
    'http://': 'http://localhost:port',  # 代理1
    'https://': 'http://localhost:port',  # 代理2  url必须写成http
}

with httpx.Client(proxies=proxies) as client:
    r1 = client.get(url, headers=headers)
    print(r1)

    print(r1.text)
    print(f'status_code : {r1.status_code}')
这个测试脚本改进了一下，我运行了一遍可以访问成功status_code是200。您看原代码里可不可以加一段代理设置呢？

**Comment by caolvchong-top** [comment]
> 
> import httpx
> 
> url = 'https://www.youtube.com/'
> 
> headers = { 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36', 'referer': 'https://www.youtube.com/' }
> 
> proxies = { 'http://': 'http://localhost:port', # 代理1 'https://': 'http://localhost:port', # 代理2 url必须写成http }
> 
> with httpx.Client(proxies=proxies) as client: r1 = client.get(url, headers=headers) print(r1)
> 
> ```
> print(r1.text)
> print(f'status_code : {r1.status_code}')
> ```
> 
> 这个测试脚本改进了一下，我运行了一遍可以访问成功status_code是200。您看原代码里可不可以加一段代理设置呢？

已更新

**Comment by niuyuxuan** [comment]
还想问一下，像这种重试有次数限制吗
![Uploading 企业微信截图_16988513979355.png…]()

**Comment by niuyuxuan** [comment]
还想问一下，像这种那个重试有次数限制吗
![test](https://github.com/caolvchong-top/twitter_download/assets/40338208/f62d21e6-24cf-4a17-86b6-6ddac059b943)

**Comment by caolvchong-top** [comment]
> 还想问一下，像这种那个重试有次数限制吗
> ![test](https://github.com/caolvchong-top/twitter_download/assets/40338208/f62d21e6-24cf-4a17-86b6-6ddac059b943)
> 

这个重试一般是网络不好，或者图片太大，导致固定时间内下载未完成，报超时

**Comment by caolvchong-top** [comment]
> 请问如果只想爬最新的信息，应该怎么设置，谢谢了

配置一下时间范围就行，［开始时间：结束时间（随便填，大于今天就行）］

**Comment by niuyuxuan** [comment]
> > 请问如果只想爬最新的信息，应该怎么设置，谢谢了
> 
> 配置一下时间范围就行，［开始时间：结束时间（随便填，大于今天就行）］
感谢
