### ISSUE TITLE
第一次使用正常，后续几天使用都报如下错误，请大神帮忙看下啥问题。

### ISSUE THREAD

**Issue by huyin324** [caolvchong-top/twitter_download#26]
PS F:\IDM下载\twitter_download-main> python .\main.py
Traceback (most recent call last):
  File "F:\IDM下载\twitter_download-main\main.py", line 50, in <module>
    settings = json.load(f)
               ^^^^^^^^^^^^
  File "C:\Anaconda\envs\python3.11\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\python3.11\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\python3.11\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 40 column 1 (char 1316)

**Comment by caolvchong-top** [comment]
settings文件有错，可以贴一下settings.json的非隐私部分吗

**Comment by huyin324** [comment]
> settings文件有错，可以贴一下settings.json的非隐私部分吗

检查了确实是setting文件错了，粘贴cookie时多了一行。
已解决，感谢！

**Comment by huyin324** [comment]
> settings文件有错，可以贴一下settings.json的非隐私部分吗

检查了确实是setting文件错了，粘贴cookie时多了一行。
已解决，感谢！
