### ISSUE TITLE
运行出现问题，为什么会有错误No module named 'httpx'

### ISSUE THREAD

**Issue by snidwn** [caolvchong-top/twitter_download#37]
不懂PY，是打开IDEL用F5运行吧。直接跳出这个错误。Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\main.py", line 4, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

**Comment by snidwn** [comment]
懂了，是缺库吧。

**Comment by snidwn** [comment]
Warning (from warnings module):
  File "C:\Users\Administrator\Downloads\main.py", line 15
    string = re.sub(u'[^\u4e00-\u9fa5\u0030-\u0039\u0041-\u005a\u0061-\u007a\u3040-\u31FF\.]', '', string)
SyntaxWarning: invalid escape sequence '\.'
>>> 
Warning (from warnings module):
  File "C:\Users\Administrator\Downloads\main.py", line 358
    re_rule = '\d{4}-\d{2}-\d{2}'
SyntaxWarning: invalid escape sequence '\d'
>>> 
= RESTART: C:\Users\Administrator\Downloads\main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\main.py", line 57, in <module>
    settings = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 17 (char 18)
装好了运行又跳这个错误，求教怎么解决。

**Comment by snidwn** [comment]
> 可以帖一下settings配置文件的非隐私部分吗
> 
> 像是配置写错了

{
    "save_path":H:/ "",
    "save_path_info": "就算是windows路径也请用 '/' ,而不是反斜杠(可以留空)",

    "user_lst":SoftCreamy2 "lilmonix3,matchach",
    "user_lst_info": "填入要下载的用户名(@后面的字符),支持多用户下载,用户名字间逗号(英文逗号,不要有空格)隔开",

    "cookie": "auth_token=c08bc7d1843c689e114fa361cf06659ae6cdcac0; ct0=bdfc1d6292c0bb5afbeb549438be65626567f02eb5059b13bbd02d5d6417bf2d34872eeb3871373c858842b45fd2f706d0d004bacf0f4cd1291ee0f1107c313a09a4c947d54efd9363d877f441ea10f4;",
    "cookie_info": "填入 cookie (auth_token与ct0字段) //重要:替换掉其中的x即可, 注意不要删掉分号",


    "emmmmmm": "以下选项三选一, 一般全false, 即 下载目标用户自己发的图片",

    "has_retweet": false,
    "has_retweet_info": "是否包含转推 (包含转推会消耗大量API调用次数)",

    "high_lights": false,
    "high_lights_info": "推特的 [Highlights]亮点 标签，与 [媒体][转推] 不共存，即仅下载亮点标签下的内容",

    "likes": false,
    "likes_info": "用户界面 [Likes] 标签页，即下载指定用户点过赞的推文，与 [媒体][转推][亮点] 不共存, 不支持时间范围限制默认全部下载(点赞时间无法获取), 不生成csv数据统计",

    "_emmmmmm_": "---------------",
    

    "time_range": "1990-01-01:2030-01-01",
    "time_range_info": "时间范围限制,格式如 1990-01-01:2030-01-01 ,不填默认无限制",

    "down_log": false,
    "down_log_info": "开启后将记录已下载的内容,避免重复下载浪费带宽; 注意:如需重新下载已下载内容,需要关闭此选项或删除目录下的 cache_data.log 文件",

    "autoSync": false,
    "autoSync_info": "开启后将基于本地已有的内容自动同步最新的部分, 本质上是自动调整时间范围的左半部分, 右半建议2030-01-01或更长, 每次运行时csv文件会被覆盖",

    "img_format": "png",
    "img_format_info": "下载图片/视频的质量(png为高质量,jpg为标准质量)",

    "has_video": true,
    "has_video_info": "是否下载推文中的视频",

    "log_output": false,
    "log_output_info": "是否需要下载过程日志输出",

    "async_down": true,
    "async_down_info": "异步下载,默认开启,网络不好时可以关闭,并发数量可在主函数11行修改",

    "proxy": "",
    "proxy_info": "手动配置代理,默认为空,非必要无需填写 格式: http://localhost:port ",


    "(๑´ڡ`๑)": "info 是注释，凑合着看吧"
}
没啥隐私，都贴出来了。

**Comment by caolvchong-top** [comment]
![image](https://github.com/caolvchong-top/twitter_download/assets/57820488/1e1e6dff-c634-4664-8b1f-92eb7d26f63f)
id应写在双引号内部，不同id间用英文逗号隔开  

另外你的cookie漏出来了，请删除你的回复，不然账号有风险

**Comment by snidwn** [comment]
"save_path": H:/"",
    "save_path_info": "就算是windows路径也请用 '/' ,而不是反斜杠(可以留空)",

    "user_lst": "SoftCreamy2",
    "user_lst_info": "填入要下载的用户名(@后面的字符),支持多用户下载,用户名字间逗号(英文逗号,不要有空格)隔开",
不好意思，改成这样了，可还是貌似一样的错误。
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\main.py", line 57, in <module>
    settings = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 18 (char 19)

**Comment by caolvchong-top** [comment]
save_path 里的 `H:/` 也需写在双引号内
