### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by wzr0108** [caolvchong-top/twitter_download#42]
下载完成显示这个error
```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E5B280C1F0>
Traceback (most recent call last):
  File "C:\Users\59476\miniconda3\envs\py39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\59476\miniconda3\envs\py39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\59476\miniconda3\envs\py39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\59476\miniconda3\envs\py39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
smart下载完成


共耗时:529.8902490139008秒
共调用3次API
共下载161份图片/视频

Process finished with exit code 0
```

**Comment by caolvchong-top** [comment]
如果没有影响下载结果的话可以不用管  

或者可以提供一下python版本和settings文件的非隐私部分

**Comment by wzr0108** [comment]
非常感谢！python==3.9.18，settings文件如下所示
```
    "emmmmmm": "以下选项三选一, 一般全false, 即 下载目标用户自己发的图片",

    "has_retweet": false,
    "has_retweet_info": "是否包含转推 (包含转推会消耗大量API调用次数)",

    "high_lights": false,
    "high_lights_info": "推特的 [Highlights]亮点 标签，与 [媒体][转推] 不共存，即仅下载亮点标签下的内容",

    "likes": false,
    "likes_info": "用户界面 [Likes] 标签页，即下载指定用户点过赞的推文，与 [媒体][转推][亮点] 不共存, 不支持时间范围限制默认全部下载(点赞时间无法获取), 不生成csv数据统计",

    "_emmmmmm_": "---------------",
    

    "time_range": "1990-01-01:2030-01-01",
    "time_range_info": "时间范围限制,格式如 1990-01-01:2030-01-01 ,不填默认无限制",

    "down_log": true,
    "down_log_info": "开启后将记录已下载的内容,避免重复下载浪费带宽; 注意:如需重新下载已下载内容,需要关闭此选项或删除目录下的 cache_data.log 文件",

    "autoSync": false,
    "autoSync_info": "开启后将基于本地已有的内容自动同步最新的部分, 本质上是自动调整时间范围的左半部分, 右半建议2030-01-01或更长, 每次运行时csv文件会被覆盖",

    "img_format": "png",
    "img_format_info": "下载图片/视频的质量(png为高质量,jpg为标准质量)",

    "has_video": true,
    "has_video_info": "是否下载推文中的视频",

    "log_output": true,
    "log_output_info": "是否需要下载过程日志输出",

    "async_down": true,
    "async_down_info": "异步下载,默认开启,网络不好时可以关闭,并发数量可在主函数11行修改",

    "proxy": "",
    "proxy_info": "手动配置代理,默认为空,非必要无需填写 格式: http://localhost:port ",


    "(๑´ڡ`๑)": "info 是注释，凑合着看吧"
```

**Comment by caolvchong-top** [comment]
这似乎是Python3.9版本的问题，换到3.10应该能解决

**Comment by wzr0108** [comment]
换成3.10已解决
