### ISSUE TITLE
请问纯文本模式也会输出api exceeded吗

### ISSUE THREAD

**Issue by qweqwsxz** [caolvchong-top/twitter_download#49]
Traceback (most recent call last):
  File "c:\Users\x\Downloads\Compressed\twitter_download-main\twitter_download-main\text_down.py", line 180, in <module>
    text_down(user)
  File "c:\Users\x\Downloads\Compressed\twitter_download-main\twitter_download-main\text_down.py", line 135, in __init__
    self.get_clean_save()
  File "c:\Users\x\Downloads\Compressed\twitter_download-main\twitter_download-main\text_down.py", line 162, in get_clean_save
    _time_stamp = int(raw_text['edit_control']['editable_until_msecs'])
                      ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'editable_until_msecs'输出了个这个 
但是输出的推文数明显就不足

**Comment by caolvchong-top** [comment]
这个是碰到了特殊推文，因为临时功能很多适配没做 

可否提供一下目标用户名

**Comment by qweqwsxz** [comment]
@bitfish1

**Comment by caolvchong-top** [comment]
已修复

**Comment by qweqwsxz** [comment]
今天才看到 重新跑了一下 并不行

**Comment by caolvchong-top** [comment]
可以提供一下错误信息吗
